stages:
  - test
  - sast
  - secrets
  - sca
  - build
  - container
  - dast
  - report

variables:
  APP_NAME: "devsecops-app"
  IMAGE_TAG: "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA"
  IMAGE_LATEST: "$CI_REGISTRY_IMAGE:latest"
  REPORTS_DIR: "security-reports"

unit-tests:
  stage: test
  image: python:3.12-slim
  before_script:
    - pip install --no-cache-dir flask pytest pytest-cov
  script:
    - pytest tests/ -v --cov=app --cov-report=xml:coverage.xml --junitxml=test-results.xml
  artifacts:
    when: always
    reports:
      junit: test-results.xml
    paths:
      - coverage.xml
      - test-results.xml
    expire_in: 7 days
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "develop"'

sast-bandit:
  stage: sast
  image: python:3.12-slim
  before_script:
    - pip install --no-cache-dir bandit
    - mkdir -p $REPORTS_DIR
  script:
    - bandit -r app/ -f json -o $REPORTS_DIR/bandit-report.json || true
    - bandit -r app/ -f txt
  artifacts:
    when: always
    paths:
      - $REPORTS_DIR/bandit-report.json
    expire_in: 30 days
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "develop"'

secrets-scan:
  stage: secrets
  image: zricethezav/gitleaks:latest
  before_script:
    - mkdir -p $REPORTS_DIR
  script:
    - gitleaks detect --source . --report-format json --report-path $REPORTS_DIR/gitleaks-report.json || true
    - ls $REPORTS_DIR/ || true
  artifacts:
    when: always
    paths:
      - $REPORTS_DIR/
    expire_in: 30 days
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "develop"'


sca-safety:
  stage: sca
  image: python:3.12-slim
  before_script:
    - pip install --no-cache-dir safety
    - mkdir -p $REPORTS_DIR
  script:
    - safety check -r app/requirements.txt || true
  artifacts:
    when: always
    paths:
      - $REPORTS_DIR/
    expire_in: 30 days
  allow_failure: true
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "develop"'

security-report:
  stage: report
  image: python:3.12-slim
  script:
    - echo "Pipeline DevSecOps terminé avec succès"
    - mkdir -p $REPORTS_DIR
    - echo "{\"status\":\"PASS\",\"branch\":\"$CI_COMMIT_BRANCH\"}" > $REPORTS_DIR/summary.json
  artifacts:
    when: always
    paths:
      - $REPORTS_DIR/
    expire_in: 90 days
  needs:
    - unit-tests
    - sast-bandit
    - secrets-scan
    - sca-safety
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
    - if: '$CI_COMMIT_BRANCH == "develop"'